### ISSUE TITLE
Doesn't seem to work with Android 8.0 emulator.

### ISSUE THREAD

**Issue by sleekweasel** [tynn/DevSet#1]
I get this in the logcat when I try on an Android 8.0 emulator:

```
07-06 08:34:59.714  1446  1461 I ActivityManager: Start proc 27893:dev.set/u0a166 for broadcast dev.set/.locale
07-06 08:34:59.714 27893 27893 W zygote  : Unexpected CPU variant for X86 using defaults: x86
07-06 08:34:59.728 27893 27893 I DevSet  : Locale=en_GB
07-06 08:34:59.729  1446  6515 W ActivityManager: Permission Denial: updatePersistentConfiguration() from pid=27893, uid=10166 requires android.permission.WRITE_SETTINGS
07-06 08:34:59.730 27893 27893 E DevSet  : null
07-06 08:34:59.730 27893 27893 E DevSet  : java.lang.reflect.InvocationTargetException
07-06 08:34:59.730 27893 27893 E DevSet  : 	at java.lang.reflect.Method.invoke(Native Method)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at dev.set.locale.onReceive(Unknown Source:88)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at android.os.Looper.loop(Looper.java:164)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at android.app.ActivityThread.main(ActivityThread.java:6540)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at java.lang.reflect.Method.invoke(Native Method)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-06 08:34:59.730 27893 27893 E DevSet  : Caused by: java.lang.SecurityException: Permission Denial: updatePersistentConfiguration() from pid=27893, uid=10166 requires android.permission.WRITE_SETTINGS
07-06 08:34:59.730 27893 27893 E DevSet  : 	at android.os.Parcel.readException(Parcel.java:1948)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at android.os.Parcel.readException(Parcel.java:1894)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at android.app.IActivityManager$Stub$Proxy.updatePersistentConfiguration(IActivityManager.java:7073)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at com.android.internal.app.LocalePicker.updateLocales(LocalePicker.java:278)
07-06 08:34:59.730 27893 27893 E DevSet  : 	at com.android.internal.app.LocalePicker.updateLocale(LocalePicker.java:262)
07-06 08:34:59.730 27893 27893 E DevSet  : 	... 11 more
```

Adding `android.permission.WRITE_SETTINGS` to the various places CHANGE_CONFIGURATION was mentioned and rebuilding from clean resulted in:

```
Operation not allowed: java.lang.SecurityException: Permission android.permission.WRITE_SETTINGS is not a changeable permission type
```

So I'm guessing this is insurmountable?

**Comment by tynn** [comment]
The required permission changed with Oreo and it cannot be set with `pm` anymore.
You have to  set this manually. Just open the write settings manager. I've updated the
required permissions in `dev` right now, so you can use it already. Will update `master`
soon. Might add an `installOreo` task maybe.

    adb shell am start -a android.settings.action.MANAGE_WRITE_SETTINGS
